name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Automatic requirements.txt for Python Project
        uses: ryan-rozario/pipreqs-action@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: AutoML   #default is the root of the repository
          REQUIREMENT_PATH: AutoML/requirements.txt  #default is requirement.txt in the root of your repository 