name: UnitTest

on:
  workflow_run:
      workflows: ['CI']
      types: [completed]
      branches: [Skelton]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Intall pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs

      - name: Commit requirements.txt
        run: |
          git config --local user.email "udriste.andrei.98@gmail.com"
          git config --local user.name "AndreiUdriste"
          git add requirements.txt
          git diff-index --quiet HEAD || git commit -m "Update requirements.txt"
          git push

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Install Dependencies
        run: 
          pip install -r requirements.txt

      - name: test_script
        run: pytest